# Generated by Django 5.2.13 on 2026-04-16 10:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('dr', 'Dr.'), ('prof_dr', 'Prof. Dr.'), ('mr', 'Mr.'), ('ms', 'Ms.')], default='dr', max_length=20)),
                ('specialty', models.CharField(choices=[('GP', 'General Practitioner'), ('CARD', 'Cardiologist'), ('DERM', 'Dermatologist'), ('PED', 'Pediatrician'), ('PSY', 'Psychiatrist'), ('ORTHO', 'Orthopedist'), ('GYNE', 'Gynecologist'), ('NEURO', 'Neurologist'), ('ONC', 'Oncologist'), ('ENDO', 'Endocrinologist')], max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?[0-9\\s\\-]{7,20}$')])),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='doctor_profiles/')),
                ('related_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
